### ISSUE TITLE
When actual release will happen of this product?

### ISSUE THREAD

**Issue by ajaysharmamca** [NewMotion/ocpi-endpoints#45]
I don't know where to ask question. 

My questions:

 When full release going to happen for this product?
 Which class will be used to plug in the database -- Where billing related information can be stored?

Also want to contribute in this project. How can I do that?

**Comment by kiequoo** [comment]
We _finally_ made a full release as this project is now pretty stable.  The project is about the OCPI interfaces, so the DB part is totally up to the user of this library.  If you want to contribute, feel free to create a PR, there are still quite a few OCPI modules we have not implemented.
